### ISSUE TITLE
Question 13

### ISSUE THREAD

**Issue by ziga-miklic** [lydiahallie/javascript-questions#10]
The answer states that only the base object does not have prototypes. Would it be a great idea to also mention that we can use `Object.create()` to explicitly remove the prototype chain:

```javascript
const foo = Object.create(null);
foo.toString() // Uncaught TypeError: foo.toString is not a function
```

Thank you again for maintaining this repo!

**Comment by lydiahallie** [comment]
Thanks for your input, this would be great to cover in a new question 👍
