### ISSUE TITLE
Answer to question 1 is a bit misleading

### ISSUE THREAD

**Issue by Andreas-Hjortland** [lydiahallie/javascript-questions#11]
Sorry about the poor title in this issue, but I didn't want to spoil the answer if people are looking at the issues before they answer the question :)

The explanation of why you get a `ReferenceError` is a bit misleading although the result is mostly the same. Technically `let` and `const` is hoisted to the top of the block scope they are declared in, but they are not initialized which makes it throw a `ReferenceError`. You can test this by running the following code:
```javascript
function outerScope() {
  let foo = 'a';
  function innerScope() {
    console.log(foo);
    let foo = 'b';
  }
  innerScope();
}
```

If we didn't have hoisting the output from this function should be 'a', but since we actually do hoist `foo` to the top of the `innerScope` function we get a `ReferenceError` since we are trying to access `foo` before initialization.

You can read more about it on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Temporal_dead_zone)

**Comment by alanlal** [comment]
Here is one more example to further illustrate the fact that `let` and `const` does get hoisted, but do not get initialized until their definition is evaluated.


```js
/* 1  */  var person = "Luke";
/* 2  */  var animal = "cat";
/* 3  */  
/* 4  */  console.log("Outside Block "+person) // "Outside Block Luke"
/* 5  */  console.log("Outside Block "+animal) // "Outside Block cat"
/* 6  */  
/* 7  */  {
/* 8  */    console.log("Inside Block "+person); // "Inside Block Luke"
/* 9  */    console.log("Inside Block "+animal); // "ReferenceError: Cannot access 'animal' before initialization
/* 10 */    let animal = "dog";
/* 11 */  }
```


The `let animal` binding is created at the beginning of the block scope. `animal` is initialized only at line _10_. Line _9_ tries to access `animal` before being initialized and hence throws a `ReferenceError`

**Comment by lydiahallie** [comment]
Thank you for your input! I have updated the answer to question 1 👍

**Comment by xerosanyam** [comment]
@Andreas-Hjortland That was a clever example. Thanks for sharing.
So the learning for future me is - all **declarations** are hoisted(be it let, var, function, const). but let & const will throw a reference error until initialized.
