### ISSUE TITLE
Small error in question 52

### ISSUE THREAD

**Issue by josselinbuils** [lydiahallie/javascript-questions#112]
Hello,

First, thanks for this, both questions and explanations are great!

However, there is small error in the question 52, the real answer is **Oh no an error! Hello world!**.

BTW, closing **"** is missing in answers **B** and **D**.

Should I create a PR ?

**Comment by vikramnr** [comment]
@josselinbuils  Yes please proceed. Add those missing `"` as well.
@lydiahallie ![image](https://user-images.githubusercontent.com/8538409/60014651-1fdc2b80-969f-11e9-8475-ba8be63a7fbc.png)

**Comment by lydiahallie** [comment]
Closing since I merged the PR
