### ISSUE TITLE
Issue with #51-whats-the-output

### ISSUE THREAD

**Issue by shivbhaw** [lydiahallie/javascript-questions#117]
Love the questions! I find myself coming back throughout the week to see if more questions have been posted. Is there any way to give you questions? I'd love to make some JavaScript brain teasers!!!

So the real issue here, question 51 has as the value being set in the function as
`year = 1998;` when it should be `year = "1998";`. It would "make" the year a number instead of a string :P nit picking but hey were aren't here to joke around! These are lives at stake here!

**Comment by lydiahallie** [comment]
Thank you! I fixed this now!
