### ISSUE TITLE
3. What's the output? 

### ISSUE THREAD

**Issue by BenjaminCrozier** [lydiahallie/javascript-questions#121]
why reverse the order of the output? seriously, why?

**Comment by papb** [comment]
What do you mean?

**Comment by A1rPun** [comment]
[This issue](https://github.com/lydiahallie/javascript-questions/issues/22) is (maybe) related #22

**Comment by A1rPun** [comment]
`shape.diameter();` returns `20`
`shape.perimeter();` returns `NaN`

**Answer B** = `20` and `NaN`.

What's wrong about the order?

**Comment by thiagosaife** [comment]
Didn't get it too.

**Comment by BenjaminCrozier** [comment]
withdrawn, I misunderstood the problem.
