### ISSUE TITLE
Question 19 - Bad usage of spread operator

### ISSUE THREAD

**Issue by mindsers** [lydiahallie/javascript-questions#127]
There is a error in the [19th question](https://github.com/lydiahallie/javascript-questions#19-whats-the-output) answer:

```js 
function getAge(...args) {
  console.log(typeof args);
}
```

The answer talks about `...args` as a _spread operator_, but in this case it is a _rest parameter_. 

**rest parameter**: `function getAge(...args) {}`
This is our case, we take all the parameters that are not explicitly named (the rest) to build an array called `args`.
**spread operator**: `getAge(...args)`
This is not our case, we use an existing array called `args` and spread it to fill the `getAge` parameters.

**Comment by lydiahallie** [comment]
You're right, rephrased it, thanks 👍
