### ISSUE TITLE
Question 1 - JavaScript Version differences in Answer

### ISSUE THREAD

**Issue by Hillsie** [lydiahallie/javascript-questions#137]
mmm... the details of this language.....I think this is where JavaScript versions confuses the correct answer. It's probably as a result of JavaScript ES6 updates and the engine changing. Try it out in different version

`node version 8.10.0
undefined
ReferenceError: age is not defined
    at sayHi (repl:3:21)
`
In a newer version

`node version 12.4.0
Thrown:
ReferenceError: Cannot access 'age' before initialization
    at sayHi (repl:3:21)
`
In the Chrome console

`
 JavaScript version 8 7.5......
Uncaught ReferenceError: Cannot access 'age' before initialization
    at sayHi (<anonymous>:3:17)
    at <anonymous>:1:1
`

Probably the mixing and matching of ES6 syntax. If you remove the `let` hoisting works as expected. ... `undefined`

some of the JavaScript community believe we should only be using ES6 syntax. `const` and `let`.

https://mathiasbynens.be/notes/es6-const

https://wesbos.com/is-var-dead/

https://wesbos.com/let-vs-const/

**Comment by lydiahallie** [comment]
All shown errors are `ReferenceError`s, like answer D. 

Indeed, it is good practice to only use `const` and `let`, however `var` is still a part of JavaScript. It's important to know the difference in behavior between `var` and `let`, as many people confuse both due to their similar behavior.
