### ISSUE TITLE
Problem 4: ";" What does that mean?

### ISSUE THREAD

**Issue by Rong-CC** [lydiahallie/javascript-questions#139]

**Comment by Rong-CC** [comment]
![image](https://user-images.githubusercontent.com/38421896/60661366-5cbcd500-9e8c-11e9-9832-4e41b9dc19f0.png)

**Comment by oshliaer** [comment]
Do you have any description for this? What's a problem?

**Comment by lydiahallie** [comment]
This is a typo. You could open a PR for this so it can be fixed 😄

**Comment by oshliaer** [comment]
@lydiahallie done!
