### ISSUE TITLE
question 66

### ISSUE THREAD

**Issue by LazyChenY** [lydiahallie/javascript-questions#152]
The last paragraph of the answer has a miswrite : 
> The `Dog` class receives two arguments, `name` since it extends `Animal`, and `size` as an extra property on the `Dog` class. They both need to be passed to the constructor function on `Dog`, which is done correctly  using constructor 2.

`Dog` -> `Labrador`， `Animal` -> `Dog`

btw，check the question 67,  I guess you copied 66  :)

**Comment by jbkly** [comment]
PR to fix: https://github.com/lydiahallie/javascript-questions/pull/154

**Comment by lydiahallie** [comment]
Thanks! This has been fixed now 👍
