### ISSUE TITLE
Suggestion a new question

### ISSUE THREAD

**Issue by oshliaer** [lydiahallie/javascript-questions#163]
@lydiahallie 

Can I PR my own question?

###### X. What's the output?

```javascript
// It is assumed that IEEE 754 https://en.wikipedia.org/wiki/IEEE_754 is applied.
function whatDifference() {
  const a = 5431234444444445000;
  const b = 5431234444444444443;
  console.log(a === b);
  console.log(a - b);
}

whatDifference();
```

- A: `false` and `557`
- B: `true` and `0`
- C: `false` and `0`
- D: `true` and `undefined`

<details><summary><b>Answer</b></summary>
<p>

#### Answer: B

You can safely perform operations with numbers up to a certain value. `Number.MAX_SAFE_INTEGER` is this value. Usually `Number.MAX_SAFE_INTEGER` is `9007199254740991`. As you can see `a` and `b` are out of the range.

Safe in this context refers to the ability to represent integers exactly and to correctly compare them. For example, `Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 2` will evaluate to true, which is mathematically incorrect.

Therefore, you do not get the mathematical correct calculations and you get what is defined.

[Read more on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)

</p>
</details>

---

**Comment by lydiahallie** [comment]
Thank you! Since I currently don't have a good way to add questions from contributors (and keep it ordered) I won't merge it yet - but I keep suggested questions in mind for sure! Thanks so much for your input, great question.

**Comment by oshliaer** [comment]
@lydiahallie  just add lables for this repo. For example "suggestion" and "suggestion (added)"
