### ISSUE TITLE
analysis of the 67th question

### ISSUE THREAD

**Issue by LazyChenY** [lydiahallie/javascript-questions#166]
I think there is another explanation.  In the second paragraph you said: 
> This means that the variable `answer` is not defined yet!

But I think,  the variable  `answer`  is defined and has a value of `undefined`, cuz the variable `answer` always has the returned value of the `yield` keyword.  `yield`  doesn't have a returned value itself or we can say it returns `undefined` by default.  When we pass a parameter to the `next` function, `undefined` is replaced with the parameter.

**Comment by chinesedfan** [comment]
> 71. How can we log the values that are commented out after the console.log statement?

Now it changed as 71st. Note that `const` is different with `var`, which has no so-called scope hoisting feature. If we added a line before the first `yield` statement to visit `answer`, it will throw an error.

```
console.log(answer);
const answer = yield "Do you love JavaScript?";
```
