### ISSUE TITLE
67题选A吧

### ISSUE THREAD

**Issue by HQHC** [lydiahallie/javascript-questions#180]

**Comment by lydiahallie** [comment]
Please provide a description in English.

**Comment by LazyChenY** [comment]
应该选B的，`import`命令是编译阶段执行的，是在代码运行之前。因此被导入的文件实际会先运行，而导入模块的文件会后执行，　所以`running sum.js`会最先被打印出来。

这是CommonJS中`require`和`import`之间的区别。使用`require()`，可以在运行代码时根据需要加载依赖项。 如果我们使用`require`而不是`import`，`running index.js`，`running sum.js`，`3`会被依次打印。
