### ISSUE TITLE
Create a PR, please.

### ISSUE THREAD

**Issue by oshliaer** [lydiahallie/javascript-questions#183]
Hi @lydiahallie!

Thanks for the repo!

Could you send a PR for merging and updating? Direct editing of the greenbranch results in the fact that we don’t see update notifications and we need to lead a specific branch for comparing (unless someone likes poking around in the long hashes of the commits).

That would be very cool!

**Comment by lydiahallie** [comment]
Oh yes of course. Will do that in the future! 😄
