### ISSUE TITLE
Question 8

### ISSUE THREAD

**Issue by Viltaria** [lydiahallie/javascript-questions#19]
In question 8, A, B, C are not possible since no values are being returned/logged

**Comment by stefanfrede** [comment]
This may solve the confusion:

```js
class Chameleon {
  static colorChange(newColor) {
    this.newColor = newColor;
  }

  constructor({ newColor = "green" } = {}) {
    this._newColor = newColor;
  }
  
  get color() {
    return this._newColor;
  }
}

const freddie = new Chameleon({ newColor: "purple" });

freddie.colorChange("orange");

console.log(freddie.color);
```

**Comment by lydiahallie** [comment]
Thanks so much! This has been fixed now 👍

**Comment by juanvillegas** [comment]
Apart from that, I believe the Answer is not entirely correct when saying that `freddie` is a "child" of Chameleon. `freddie` is just an Instance of (an object constructed by) Chameleon.
