### ISSUE TITLE
The answer to question 76 is wrong.

### ISSUE THREAD

**Issue by qiufeihong2018** [lydiahallie/javascript-questions#190]
The result of implementation is
![JS76](https://user-images.githubusercontent.com/36500514/62188156-23e62200-b39e-11e9-9988-5f25afa9b4d7.png)

**Comment by oshliaer** [comment]
On the other hand

![1564561590553](https://user-images.githubusercontent.com/5027939/62196118-14f37580-b386-11e9-8a66-62abcb94583e.png)

**Comment by oshliaer** [comment]
@qiufeihong2018 , 

Please, visit `chrome://flags/#enable-javascript-harmony` and enable the flag before check latest features in your browser.

**Comment by qiufeihong2018** [comment]
@oshliaer But there is no precondition for deleting name.So I still believe in undefined.

**Comment by oshliaer** [comment]
> But there is no precondition for deleting name.So I still believe in undefined.

This is because your environment may be unclean. A variable named `name` can easily leak into the global context, because many variables with the same name exist. Replace the name of this variable with something more unique.

How about this?

```js
const { qiufeihong2018: myName } = { qiufeihong2018 : "Lydia" };

console.log(qiufeihong2018);
```

**Comment by oshliaer** [comment]
You must also be sure that the variable `name` does not exist. If you started the deletion `delete name` and it returned `true`, it means that your environment already had a variable `name`. You cannot get `ReferenceError` error in this situation.

**Comment by qiufeihong2018** [comment]
@oshliaer I'm understand!Thank you!

**Comment by oshliaer** [comment]
@qiufeihong2018 you can close the issue.

**Comment by chinesedfan** [comment]
`window.name` is a useful but not recommended way to implement cross-domain messaging. It is always there. :)

**Comment by xtabay** [comment]
But would not be more more correct to use variable which not crossing with browser web API (e.g. `const { someName: myName } = { name: "Lydia" };`) or add answer like (`depends from execution enviroment`)?
