### ISSUE TITLE
Clarify answer about functions in question 10

### ISSUE THREAD

**Issue by RinatValiullov** [lydiahallie/javascript-questions#191]
I think it would be more informative to clarify that **functions are first-class objects**
in question 10th:
https://github.com/lydiahallie/javascript-questions#10-what-happens-when-we-do-this

**Comment by A1rPun** [comment]
@RinatValiullov What is the difference between `objects` and `first-class objects` in JavaScript according to you? I'm asking this just to know what information we will gain.

**Comment by RinatValiullov** [comment]
Hope this will explain better than me:
[First-class citizen](https://en.wikipedia.org/wiki/First-class_citizen#Functions)

Compare to other languages it become valuable (just for clarification). But you can leave as `objects`

**Comment by A1rPun** [comment]
If someone is coming from another language it will add some value, I agree.

**Comment by RinatValiullov** [comment]
@A1rPun Found this article about `First-Class Functions`

[First-Class Functions in JavaScript](https://nick.scialli.me/first-class-functions-in-javascript/)
