### ISSUE TITLE
Split questions into categories

### ISSUE THREAD

**Issue by jakeherp** [lydiahallie/javascript-questions#193]
Considering this there are going to be close to 100 questions with the next update, would it make sense to split them up into several categories, essentially creating a folder structure for languages (`./` for english, `es-ES` for Spanish and so on), with a landing `README.md` for each language with several other markdown files for each category?

I appreciate that this would add complexity to this project, but might make it easier for users to find the questions they are most interested in?

**Comment by lydiahallie** [comment]
I agree, I've been thinking about this too. I'm not sure whether I want to go for a folder structure such as:

```
- README.md
- README_de-DE.md
- README_pt-PT.md
- README_ua-UA.md
- Hoisting/
   ├── README.md
   ├── README_de-DE.md
   ├── README_pt-PT.md
   └── README_ua-UA.md
- Classes/
   ├── README.md
   ├── README_de-DE.md
   ├── README_pt-PT.md
   └── README_ua-UA.md
```

Or: 

```
- English/
├── README.md
├── Hoisting/
│   └── README.md
└──Classes/
   └── README.md
- German/
├── README.md
├── Hoisting/
│   └── README.md
└── Classes/
       └── README.md
 
```
Et cetera. Let me know if you prefer one over the other.

**Comment by oshliaer** [comment]
How about ?
```
...
├── ua-UA
├── de-DE
│   ├── README.md
│   ├── Q10.md
│   ├── Q20.md
│   └── Q30.md
├── pt-PT
│   ├── README.md
│   ├── Q10.md
│   ├── Q20.md
│   └── Q30.md
└── README.md
```
`/README.md` is filled with links to langs
`/de-DE/README.md` is filled with categories and links as you like

* Hoisting
  * Q2
  * Q222
* Classes
  * Q3
  * Q 333

And on the same file

* Q1
* Q2

And on the same file

* Intermediate
  * Q3
  * Q 333
* Advanced
  * Q3
  * Q 333
* Proficiency
  * Q3
  * Q 333

Don't mix langs please. Look at here https://github.com/i0natan/nodebestpractices/tree/master/sections/security It's like a mini hell https://github.com/i0natan/nodebestpractices/pull/444

**Comment by lydiahallie** [comment]
@oshliaer I like your approach! I won't split the questions themselves intoseparate `.md` files but rather create a `README.md` for every folder,  such as "Classes", which will contain the filtered questions. 

```
...
├── ua-UA
│   ├── README.md
│   ├── Classes
│   │     └── README.md
│   └── Hoisting
│         └── README.md
├── de-DE
│   ├── README.md
│   ├── Classes
│   │     └── README.md
│   └── Hoisting
│         └── README.md
├── pt-PT
│   ├── README.md
│   ├── Classes
│   │     └── README.md
│   └── Hoisting
│         └── README.md
├── en-EN
│   ├── README.md
│   ├── Classes
│   │     └── README.md
│   └── Hoisting
│         └── README.md
└── README.md
```


If this makes sense, I'll add it to the next batch of questions 👍

**Comment by oshliaer** [comment]
Fine! Waiting for edits! :rocket:

**Comment by jakeherp** [comment]
I think this is a great approach!
Considering somebody is interested in a certain language it makes sense to categorise by language in the first place and then splitting by topic.

**Comment by A1rPun** [comment]
Should the folder/file names like Classes, Hoisting or README be translated to the language folder they are in? Probably makes it more complex.

**Comment by jakeherp** [comment]
Having done the German translation I feel like the best approach is to keep those things in English. Not sure if this works for all other languages, but since programming paradigms are generally in English, these categories can remain in English, too.

**Comment by lydiahallie** [comment]
@A1rPun No, we should keep the English terms such as "hoisting" and "classes". It would be confusing to translate them

**Comment by oshliaer** [comment]
> Not sure if this works for all other languages

This is probably a global practice when we use a mixed language for technical terms. This speeds up interlanguage interaction.
