### ISSUE TITLE
question 90 and 92 answer is wrong

### ISSUE THREAD

**Issue by ChenCong6837** [lydiahallie/javascript-questions#196]
question 90 :
class Person {
  constructor(name) {
    this.name = name
  }
}

const member = new Person("John")
console.log(typeof member)  // object

typeof member is object, but the answer is B (function)

question 92 :
function giveLydiaPizza() {
  return "Here is pizza!"
}

function giveLydiaChocolate() {
  return "Here's chocolate... now go hit the gym already."
}

console.log(giveLydiaPizza.prototype) 
console.log(giveLydiaChocolate.prototype)
true answer is : A: { constructor: ...} { constructor: ...}

**Comment by oshliaer** [comment]
# 90

It seems you're right. Because this is same as

```js
function Person(name) {
  this.name = name;
}

var member = new Person("John");
console.log(typeof member); // $> object 
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new
> The new operator lets developers create an instance of a user-defined object type or of one of the built-in object types that has a constructor function.

**Comment by lydiahallie** [comment]
Thanks! This has been fixed now 👍
