### ISSUE TITLE
https://www.instagram.com/theavocoder cannot found 

### ISSUE THREAD

**Issue by pbwei** [lydiahallie/javascript-questions#209]
this is china

**Comment by A1rPun** [comment]
> Yes, Instagram is blocked in China. It was blocked intermittently starting in 2014 and now it is completely censored. Attempting to access the app from within mainland China will result in an error message saying the feed cannot be refreshed. Instagram is also absent from Chinese app stores.

Solution: VPN

**Comment by oshliaer** [comment]
eslint.org and babel.io blocked in Russia!  Whose hospital is stronger?

**Comment by A1rPun** [comment]
@oshliaer Damn I didn't know open-source like [babeljs.io](https://babeljs.io/) is blocked in Russia. First github is blocking Iran and Syria from open-source... now this.

**Comment by oshliaer** [comment]
Of course, they simply block IP, not realizing that this IP has long been a different site.

**Comment by lydiahallie** [comment]
Can't help with this unfortunately 😅

**Comment by EvanBacon** [comment]
+1 plz fix
