### ISSUE TITLE
Duplicated Question Number 12

### ISSUE THREAD

**Issue by ExTEnS10N** [lydiahallie/javascript-questions#21]
https://github.com/lydiahallie/javascript-questions#12-whats-the-output
https://github.com/lydiahallie/javascript-questions#12-what-are-the-three-phases-of-event-propagation

See that? They are both Question 12.

**Comment by ExTEnS10N** [comment]
And Question 19 disappeared.

**Comment by lydiahallie** [comment]
Thank you so much! This has been fixed now 👍
