### ISSUE TITLE
Question 3 - no output

### ISSUE THREAD

**Issue by yaronuliel** [lydiahallie/javascript-questions#22]
In question 3 the question asks "what is the output?" while in fact the code doesn't produce any output (no `console.log` or anything else)

**Comment by hooseinsaid** [comment]
it's obviously asking for the return value then.

**Comment by Coder2012** [comment]
Maybe it is asking for the return value, but it's still incorrect. The answer is B as below:

`B: 20 and NaN`

But the description says - There is no value radius on that object, which returns undefined.

But none of the answers have `undefined`

**Comment by yaronuliel** [comment]
@Coder2012 He meant that inside `perimeter` - the value of `this.radius` is `undefined` - and therefore the result of `2 * Math.PI * this.radius` (`2 * Math.PI * undefined`) is `NaN`

@hooseinsaid Regarding the "output" vs "return" wording - I think that the question should depict what the actual code does (actually, it does not return anything as well). But of course this is a minor thing

**Comment by A1rPun** [comment]
Just add `console.log` (there are 43 in other questions already).
```js
console.log(shape.diameter());
console.log(shape.perimeter());
```

**Comment by lydiahallie** [comment]
Thanks, fixed 👍
