### ISSUE TITLE
Difference between chrome and firefox while printing a set (Question 56)

### ISSUE THREAD

**Issue by akashdsouza** [lydiahallie/javascript-questions#243]
First of all, I appreciate all the work put into this repo.

Firefox:
<img width="473" alt="Screen Shot 2019-09-30 at 7 21 14 PM" src="https://user-images.githubusercontent.com/13344933/65885203-d135e000-e3b7-11e9-8a36-5ddc946841fc.png">

Chome:
<img width="568" alt="Screen Shot 2019-09-30 at 7 21 00 PM" src="https://user-images.githubusercontent.com/13344933/65885220-dabf4800-e3b7-11e9-9008-8669a237634e.png">

While this isn't a problem relating to this repo itself, the options for question 56 may be confusing as both answers are listed.

**Comment by lydiahallie** [comment]
Good catch, I didn't know that. Instead of rewriting the question, I'll add clarification to the description that I base my answers only on Chrome and Node 😄
