### ISSUE TITLE
Question 17

### ISSUE THREAD

**Issue by danrevah** [lydiahallie/javascript-questions#25]
Great job on the repo :)

Regarding question 17, it might be worth mentioning that the array also have a special raw strings property.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Raw_strings

**Comment by lydiahallie** [comment]
Thanks for your input! This seems like good information for a new question to not make the answers _too_ elaborate. Will consider this for future questions.
