### ISSUE TITLE
#5 with wrong translation in modul  of zh_CN

### ISSUE THREAD

**Issue by ViavaCos** [lydiahallie/javascript-questions#265]
As the question that  both of A&D are **all not valid**.

The correct options from en-EN as below:

A: mouse.bird.size is not valid
B: mouse[bird.size] is not valid
C: mouse[bird["size"]] is not valid
D: All of them are valid

--------------------------------------------------------------------------------
Thank you for your perfect structural design of those questions!
It's very useful for reader!

**Comment by lydiahallie** [comment]
Thank you for your issue! Could you maybe create a PR to update the Chinese translation with the correct options? 😄
