### ISSUE TITLE
Q118 Missed answers

### ISSUE THREAD

**Issue by contributorpw** [lydiahallie/javascript-questions#277]
@lydiahallie Hi! It seems there are missed answers in Q118

![1574747925764](https://user-images.githubusercontent.com/5027939/69603265-2b0afd00-102b-11ea-88a1-f038538e3fa2.png)

**Comment by tshinnic** [comment]
Sorry, not seeing the problem, under Chrome 79 and 81, Firefox 71 and 72, nor Edge 44, and Android cellphone is also again.

![LydiaHallie_118_1](https://user-images.githubusercontent.com/842881/71054196-b4878980-2116-11ea-8574-f500ca8a3ab0.jpg)

I'll note the following about the particular emoji character, "🥰"
This works out to be Unicode emoji character 0x01F970 aka "smiling face with hearts"
This was not added to Unicode until version 11.0: https://www.unicode.org/charts/PDF/Unicode-11.0/U110-1F900.pdf
Looking at Unicode version history I find:
Coming is 13.0
Current is 12.1.0 - 2019/05/07
Previous was 12.0 - 2019/03/05
Previous was 11.0 - 2018/06/05

Is it possible you are using a browser that has not been updated to more recent Unicode versions, *or* that the OS system fonts available to you do not have these newer characters?

**Comment by contributorpw** [comment]
Thanks! It seems my GC skips this. My FF is fine.
