### ISSUE TITLE
Q119 Strange markers/operands

### ISSUE THREAD

**Issue by contributorpw** [lydiahallie/javascript-questions#278]
@lydiahallie Hi! What is `?` meaning?

![1574749201472](https://user-images.githubusercontent.com/5027939/69604303-0ebc8f80-102e-11ea-8ec1-29c2019a28ba.png)

**Comment by contributorpw** [comment]
OK. It's a proposal https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

But with the presets I cant reach the correct answer. I got
![1574750537727](https://user-images.githubusercontent.com/5027939/69605427-221d2a00-1031-11ea-896a-9b643e1a0305.png)

It seems the correct answer is `Mara` `undefined` `Lydia Hallie` `ReferenceError`. But it's out of there.

Please correct me.

**Comment by Shoulao** [comment]
Ok, I see the point now. Sure, should be Ref error since there is no such an object as member. ?. checks only if the property of the object is ok. I think it should be as u wrote.

**Comment by contributorpw** [comment]
Thank you for the review! This is encouraging!

**Comment by tshinnic** [comment]
Checked just now with Chrome 81 (canary)
```
> console.log(member.getLastName?.());
  Uncaught ReferenceError: member is not defined
    at <anonymous>:1:13
```
so suggested fix is correct

**Comment by contributorpw** [comment]
@tshinnic 

It's on Canary already! So fast!
