### ISSUE TITLE
Q145. Wrong code for correct answer.

### ISSUE THREAD

**Issue by idldmit** [lydiahallie/javascript-questions#299]
Q145. Says answer is 
C: *[Symbol.iterator]() { for (let x in this) yield* Object.values(this) }
but because of loop it leads to ["Lydia Hallie", 21, "Lydia Hallie", 21] instead of ["Lydia Hallie", 21]

**Comment by jakeknerr** [comment]
see https://github.com/lydiahallie/javascript-questions/pull/292
