### ISSUE TITLE
[DUTCH] You people want to help me out translate it to NL?

### ISSUE THREAD

**Issue by Tarabass** [lydiahallie/javascript-questions#307]
Hi there,

I'm translating the questions into dutch. Maybe someone can help me by translate some questions too. I've created a branch on my fork so we can safely work on it and when we are finished we can merge it into Lydia's master.

https://github.com/Tarabass/javascript-questions/tree/NL_Translations

I updated the README's for the other languages already, translated the preface on the NL README and started to translate the questions.

I suggest we commit every translated question one by one. We can keep each other informed in this thread which questions we will translate.

**Comment by lydiahallie** [comment]
Thanks for your contribution! I won't have time to help you translate this unfortunately, but while you're working on it you could open a draft PR so other people can see you're working on it (to avoid duplication, and maybe get more contributors) 😃

**Comment by Tarabass** [comment]
It's finished: https://github.com/lydiahallie/javascript-questions/pull/312
