### ISSUE TITLE
Answer of question 65 is incorrect

### ISSUE THREAD

**Issue by Tarabass** [lydiahallie/javascript-questions#320]
> The first argument that the `reduce` method receives is the _accumulator_, `x` in this case. The second argument is the _current value_, `y`. With the reduce method, we execute a callback function on every element in the array, which could ultimately result in one single value. 

The first argument of the `reduce` method is not the _accumulator_. The first argument of the `reduce` method is a `callback` function, also called a _reducer function_. The first argument of the _reducer function_, which takes four arguments, is the _accumulator_,

[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)

**Comment by karkranikhil** [comment]
Let me fix

**Comment by EugeneGohh** [comment]
Can I work on this issue? @jakeherp @Tarabass

**Comment by gaurav8y785675474** [comment]
hello @Tarabass 
i solved this question and console it. but answer is correct.
thank you.
