### ISSUE TITLE
The answer  of question 114, is the "this" problem!

### ISSUE THREAD

**Issue by ShyarK** [lydiahallie/javascript-questions#323]
I think the problem is because of <strong>"this"</strong> keyword :
Code executed by setInterval() runs in a separate execution context than the function from which it was called. As a consequence, the this keyword for the called function is set to the window (or global) object, it is not the same as the this value for the function that called setTimeout.
I tried with both arrow and regular functions, and for both I got window object as the value of this!

Please take a look at
 <a href="https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval/#The_this_problem">MDN</a>

**Comment by beginWithJS** [comment]
It seems like does not matter the funciton is a arrow function or not. I put  a normal funciton in there, it is still be called every second. Is there a way to check out the object  get garbage collected or not?
