### ISSUE TITLE
Question 9 – clarify for ES modules

### ISSUE THREAD

**Issue by loilo** [lydiahallie/javascript-questions#33]
With ES modules [always using strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Strict_mode_for_modules), the answer for [question 9](https://github.com/lydiahallie/javascript-questions#9-whats-the-output) is no longer unambiguous: Since all modern browsers support modules, it's not clear whether the code snippet uses strict mode or not (which would change the correct answer from A to B), therefore the question should probably be clarified. :)

**Comment by loilo** [comment]
This similarly applies to other questions as well (e.g. question 12, where the correct answer in strict mode would be `Person {firstName: "Lydia", lastName: "Hallie"}` and `TypeError`).

**Comment by lydiahallie** [comment]
In all questions, I assume it's not strict mode unless otherwise specified. However I should probably make this more clear to avoid confusion. I will do this in the new batch of questions, thanks for your input!

**Comment by xgqfrms** [comment]
> With ES modules [always using strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Strict_mode_for_modules), the answer for [question 9](https://github.com/lydiahallie/javascript-questions#9-whats-the-output) is no longer unambiguous: Since all modern browsers support modules, it's not clear whether the code snippet uses strict mode or not (which would change the correct answer from A to B), therefore the question should probably be clarified. :)

# same question

https://github.com/lydiahallie/javascript-questions/issues/210
