### ISSUE TITLE
[fix] question #76

### ISSUE THREAD

**Issue by lavfrim** [lydiahallie/javascript-questions#331]
###### 76. What's the output?

```javascript
const { name: myName } = { name: "Lydia" };

console.log(name);
```

- A: `"Lydia"`
- B: `""`
- C: `undefined`
- D: `ReferenceError`

#### Answer: B

When we unpack the `name` property from the right object, we assign its value` `Lydia '' to a variable named` myName`.

Using `{ name: myName }` we tell JavaScript that we want to create a new variable named `myName` with the value of the `name` property on the right side.

Since we are trying to output `name` to the console as a global variable (`this.name`, to be more precise `window.name`), we will get ` "" ` because in the global scope,`<empty string>` is reserved for `name`.

If the variable name were different, for example, `bestGirlName` and the code would look:
```javascript
const {bestGirlName: myName} = {bestGirlName: "Lydia"};

console.log (bestGirlName);
```
That console would throw a ReferenceError.

**Comment by jbbn** [comment]
Very trick one @lavfrim 😄

But in the question you don't specify that the environment is a **browser**.

This is JavaScript and we could also run this in a **NodeJS** environment, which throws a `ReferenceError`.

See an example using REPL:
![Screen Shot 2020-02-14 at 21 28 28](https://user-images.githubusercontent.com/3846247/74578013-fa26ce00-4f70-11ea-94a1-0cff77da8224.png)

**Comment by lavfrim** [comment]
ty @jbbn
I did not know that the global objects of node.js `global` and the browser `window` will differ by this ^_^

Yes,  at `window`  we have several names, such as `window.name`, `window.status` which are equal to ` "" `

I think that maybe it’s not worthwhile to pay attention to such subtle differences in the global objects of the node.js `global` and the browser `window` in the context of this example. And just specify a neutral name which will not be in `windows` and the `global`  =)

**Comment by jbbn** [comment]
yw, I'm glad to be useful.

yes @lavfrim I agree, just using a neutral variable name would be enough; this way, the question will not have two valid answers available 🚀 

what do you think about this topic @lydiahallie? (and thanks for creating this repo and do such a great job sharing all of this with us 🙏 💪)

**Comment by lydiahallie** [comment]
Hey! Thanks for bringing this up, nice catch! 😄

You're totally right, if you run this in your browser console you'll see an empty string. I didn't mention this in the question, and I definitely should! 

In most of my questions, I assume that it's run in a Node environment rather than a browser environment, unless I specifically add `window`.  I noticed that this is not clear to the readers, my apologies!

I will change the question to clarify that the reader should assume this code runs in a Node environment. Thank you! 😄

**Comment by vamsi99986** [comment]
yaah.. really  useful...
