### ISSUE TITLE
Question 35 and BigInt

### ISSUE THREAD

**Issue by tkalmi** [lydiahallie/javascript-questions#363]
In the answer to Question 35 ("Which of these values are falsy?"), it says that there are only six values that are falsy:
- `undefined`
- `null`
- `NaN`
- `0`
- `''` (empty string)
- `false`

However, also the `BigInt` zero, or `0n` is a falsy value.

**Comment by leonlafa** [comment]
I agree @tkalmi ,  PR awaiting approval:
https://github.com/lydiahallie/javascript-questions/pull/379
