### ISSUE TITLE
Question 57 - Incorrect Explanation

### ISSUE THREAD

**Issue by simov** [lydiahallie/javascript-questions#365]
The explanation in question 57 states that imported modules are _read-only_ when what actually happens is that the imported values are imported as if they were defined with `const` in your current module.

Here is another interesting example that can be added to the list, that proves the `const` thing, and invalidates the _read-only_ bits:

```js
// obj.js
let obj = {foo: 'bar'}
export default obj
// mutate.js
import obj from './obj.js'
obj.baz = 'boo'
// index.js
import './mutate.js'
import obj from './obj.js'
console.log(obj)
```

I'll let you guess what's the output of this.

**Comment by lovetingyuan** [comment]
obj will be `{ foo: 'bar', baz: 'boo' }`
the situation is just like you define an object variable with `const`, you can change property of this object, but you can not  assign new value to the variable.

**Comment by simov** [comment]
Exactly, all I'm saying is that the explanation is misleading as it is right now. I think explaining it with `const` will be much closer to what it really is.
