### ISSUE TITLE
Create public web API base on this repo

### ISSUE THREAD

**Issue by marekdano** [lydiahallie/javascript-questions#366]
Big thanks for creating this great repo with javascript questions!!!

I thought about creating public web API with javascript questions from this repo. Then the web API can be used for some applications e.g. JS quiz.

What do you think?

**Comment by tomByrer** [comment]
I thought about making an API, but the actual JSON is still small (& much smaller if GZiped), so IMHO.  So for right now, it is just a CLI script with the single-file JSON output:

https://github.com/tomByrer/markdown-quiz-to-json

Linda made it very easy to create this: 99.5% of the entries are easy to RegEx.
