### ISSUE TITLE
Discussion: question 77 need clarification

### ISSUE THREAD

**Issue by RidgeA** [lydiahallie/javascript-questions#369]
Question: https://github.com/lydiahallie/javascript-questions/blob/master/README.md#77-is-this-a-pure-function

I could imagine a situation where the function won't be pure.

```
let x = {
  [Symbol.toPrimitive]: () => {
    console.log('side effect');
    return 1
  }
}

let y = {
  [Symbol.toPrimitive]: () => {
    console.log('another side effect');
    return 2
  }
}

function sum(a, b) {
  return a + b
}

sum(x, y);
```

In this case, `sum` function will return `3`, but all console.log are executed.
Obviously, this is a corner case, but....

**Comment by vinodkumartheking** [comment]
To best of my knowledge, a pure function is something which will return same result for same inputs, more kind of mathematical formula, !

**Comment by RidgeA** [comment]
That's true, but it is not enough. 
Another mandatory property is absence of side effects. 
https://en.m.wikipedia.org/wiki/Pure_function

`console.log` is a side effect

**Comment by vinodkumartheking** [comment]
@RidgeA  Yes, i agree. the above code now become not a pure function ! Thanks for the explaination.

**Comment by Lionad-Morotar** [comment]
hhh~ I just wanted to create an issue.

![image](https://user-images.githubusercontent.com/26913795/88008096-07f50680-cb42-11ea-99ea-8ba00c761cc1.png)
