### ISSUE TITLE
Question 98: a syntax error in arrow function declaration

### ISSUE THREAD

**Issue by fengtomy** [lydiahallie/javascript-questions#377]
```
const getUser = user => { name: user.name, age: user.age }
```
here exists a syntax error at `age:`

**Comment by rciupei** [comment]
it should be with extra parantheses `const getUser = user => ({ name: user.name, age: user.age })`

**Comment by leonlafa** [comment]
I've just submitted a PR for the fix guys:
https://github.com/lydiahallie/javascript-questions/pull/378
