### ISSUE TITLE
https://github.com/lydiahallie/javascript-questions#11-whats-the-output

### ISSUE THREAD

**Issue by vibhor-vp** [lydiahallie/javascript-questions#386]
Hi,

Awesome work on the repo.
But there is one issue that the solution to the question-11 says, 'You can't add properties to a constructor like you can with regular objects'.
This is a wrong statement, because we can add property to the constructor functions also, its just that it will not be accessible to any child who inherits from the constructor function(as explained in the remaining answer).

**Comment by chinesedfan** [comment]
Seems solved now.
