### ISSUE TITLE
Question 39: is it an object or not?

### ISSUE THREAD

**Issue by DavidSint** [lydiahallie/javascript-questions#398]
It says in the answer:
> JavaScript will implicitly wrap the object using one of the wrapper classes, i.e. `String`

But this seems to refer to the primitive as an object.

Which is it? An object or not an object? 😖

**Comment by regchiu** [comment]
`string` is primitive type.

`String` is an object.

**Comment by DavidSint** [comment]
But then that sentence says that the object is being wrapped in another object?

So should the sentence be:
> JavaScript will implicitly wrap the primitive type using one of the wrapper classes, i.e. `String`

Or am I misunderstanding something?

**Comment by jakeherp** [comment]
Merged #400
