### ISSUE TITLE
Question 23 - adjusting the answer

### ISSUE THREAD

**Issue by LukasBicus** [lydiahallie/javascript-questions#399]
Hi, I tested question 23 in the chrome console. See this:
![Screenshot 2020-08-19 at 10 19 04](https://user-images.githubusercontent.com/5645414/90610486-c4a3bb80-e205-11ea-82dd-69a43363499c.png)

Based on the test, I think, `let` behaves just like `var`, when trying to redefine. Because of that, I suggest to replace:
```
You cannot do this with let or const since they're block-scoped.
```
With 
```
Let behaves similar to var. const would throw SyntaxError, as it is block-scoped.
```

**Comment by jakeherp** [comment]
Hi @LukasBicus,
I am closing this, as it is in fact correct, that both `let` and `const` are block-scoped. The difference is, that `let` can be redeclared, whereas `const` (= constant) cannot be redeclared, once a value has been assigned to it.
