### ISSUE TITLE
The 24th question

### ISSUE THREAD

**Issue by smellyshovel** [lydiahallie/javascript-questions#44]
> The JavaScript global execution context creates two things for you: the global object, and the "this" keyword.

Technically, there's no such thing as a "global execution context". I mean in terms of terminology at least.

If you take a look at [the spec](http://ecma-international.org/ecma-262/), you won't be able to find a single mention of the "global execution context"; however, [there's a thing called "global lexical environment"](http://ecma-international.org/ecma-262/#global-environment), which is, I believe, is what you're talking about in that question.

And, if we dig even further, [it becomes obvious](http://ecma-international.org/ecma-262/#table-18) that the `this` keyword is a property of the global environment's *environment record*, rather than the global env. itself, but that one is not really important (if not the same in some way).

In general, my point is that you should change the wording of the question to avoid ambiguities and in order to stick stricter to the official terminology.

**Comment by oldrich-s** [comment]
there is also no global this in service workers ;)

**Comment by KL13NT** [comment]
I guess the explanation is meant for people who are not experts and don't actually look into the spec itself. "Global execution context" to a newbie's ears is way easier to understand than "Global lexical environment" and "environment record". Could be useful though that it gets added as an additional part to the explanation, explaining what is meant by "Global execution context".
