### ISSUE TITLE
Question 2

### ISSUE THREAD

**Issue by klaimmore** [lydiahallie/javascript-questions#45]
I think the wording of answer to question 2 can be improved a bit:
It is not the `setTimeout` function that is called after the loop, it is the setTimeout's function *argument*.
The variable `i` in the first loop was declared using `var`, hence it is function-scoped to whatever containing function that for loop belongs to, it is only global when there is no such function.

**Comment by lydiahallie** [comment]
Great catch! Will update this to `the function callback` 👍
