### ISSUE TITLE
gamify? notify?

### ISSUE THREAD

**Issue by gabrielsroka** [lydiahallie/javascript-questions#49]
Hi,

I really enjoyed these. Any thoughts about keeping score to gamify it (or just know how well you did)? Also, it would be great to be notified (preferably by email, I don't use instagram) when you publish new ones. Is there a way to do this?

Thanks!

**Comment by lydiahallie** [comment]
This is a great idea. I will definitely look into this! Generally, I will post new questions every Thursday, however I will definitely set up some notification system. I'll keep this issue open in case some people have good ideas on how to do this 😄

**Comment by gabrielsroka** [comment]
https://www.jshero.net
is free software:
https://github.com/strenkel/jshero

it's different than yours, but might be worth looking at. it doesn't actually keep score, but it changes questions from red to green when they've been answered correctly (passed the unit test)

**Comment by gabrielsroka** [comment]
Or maybe something like https://kahoot.com/ . There's probably a ton of ways to do it, if only i could google it :)

**Comment by naholyr** [comment]
FYI I published `javascript-questions-cli` to npm for fun, you can use it meanwhile to keep track of your progress:

```sh
npx javascript-questions-cli
```

Note: never run commands provided by strangers without verification, you can check out the code right here to ensure safety → https://github.com/naholyr/javascript-questions-cli

**Comment by lydiahallie** [comment]
You can now sign up [here](https://www.theavocoder.com/subscribe) if you want to receive updates when I've added new questions 😄

**Comment by oshliaer** [comment]
Vote for javascript-questions-cli! :+1:

**Comment by Aldinco** [comment]
> Or maybe something like https://kahoot.com/ . There's probably a ton of ways to do it, if only i could google it :)

I was planning to have a JS-quiz at work and found this awesome repo. So I took the first 60 questions and made a Kahoot Quiz. I'll try it out this Wednesday and if it all goes well, I'll add the rest of the questions in it and share! :-)

**Comment by guillaumeviel** [comment]
I have updated the code published by naholyr to work with the current version of the readme, and changed it to pick questions randomly: [javascript-questions-random-cli](https://www.npmjs.com/package/javascript-questions-random-cli)
