### ISSUE TITLE
Question 114

### ISSUE THREAD

**Issue by ravi-teja-nani** [lydiahallie/javascript-questions#505]
You mentioned this in answer _"However, since the callback function within setInterval is an **arrow function** (thus bound to the config object), the callback function still holds a reference to the config object."_

But this will work for anonymous and named functions too!!

**Comment by lenmorld** [comment]
I opened a PR for this, clarfying that the right way to clear an interval is via `clearInterval`
https://github.com/lydiahallie/javascript-questions/pull/537

**Comment by ravi-teja-nani** [comment]
I think now the explanation it is prefect, closing this issue now.
