### ISSUE TITLE
Can I add basic statistics on your quiz website?

### ISSUE THREAD

**Issue by Gummybearr** [lydiahallie/javascript-questions#506]
Hi

I'm a big fan of your project.

I also visited your website, and thought it would be interesting for users if they can check how tricky the question is and how many people actually managed to solve the quiz.

So I came up with an idea to link statistics on javascript-quiz website.

Can I contribute to your project by adding basic bar/pie chart at the bottom of your website for every quiz?

Or if there is better suggestions, I'd be happy to hear

Have a great day:)

**Comment by Gummybearr** [comment]
Also, I think the statement of Q136 at https://javascript-quiz.com/136 is different from the one in this repository. If the website belong to you, I would be happy to fix it for you as well:)

**Comment by medic-code** [comment]
@Gummybearr I don't see any difference ? Unless 136 has been changed already.

**Comment by Gummybearr** [comment]
@medic-code I guess the website has been updated. I remember there were like 137 questions when I opened up this issue.
