### ISSUE TITLE
question 3

### ISSUE THREAD

**Issue by aizuyan** [lydiahallie/javascript-questions#52]
Frankly, i think 【the `this` keyword refers to its definition surrounding scope】 is more suitable than 【the `this` keyword refers to its current surrounding scope】

for example:

`shape.perimeter.call(shape)` still return `NaN`，but its current surrounding scope `this` point shape.

**Comment by A1rPun** [comment]
Good issue :+1: 

Yes you can bind, call or apply context to functions but I think adding *definition* will complicate the context of this question.
Later in that question, *surrounding scope* is written without *current* so maybe it can be removed?

**Comment by lydiahallie** [comment]
Do you mean `its definitions surrounding scope`?

**Comment by aizuyan** [comment]
Yes

**Comment by shuofenghao** [comment]
According to this method, the result can be obtained. Results are as follows
class shape {
  radius = 10;
  perimeter = () => 2 * Math.PI * this.radius;
}
const newShape = new shape();
console.log(newShape.perimeter());

But I still don't understand why it was wrong.

**Comment by aizuyan** [comment]
use [babel](https://www.babeljs.cn/repl) to translate, such as :
```js
const shape = {
  radius: 10,
  diameter() {
    return this.radius * 2;
  },
  perimeter: () => 2 * Math.PI * this.radius
};
```

**TO**

```js
"use strict";

var _this = void 0;

var shape = {
  radius: 10,
  diameter: function diameter() {
    return this.radius * 2;
  },
  perimeter: function perimeter() {
    return 2 * Math.PI * _this.radius;
  }
};
```

We can see that arrow function's `this` point to it's definition's surrounding scope.

**Comment by shuofenghao** [comment]
Maybe I prefer to use this way.
class shape {
  radius = 10;
  perimeter = () => 2 * Math.PI * this.radius;
}
const newShape = new shape;
console.log(newShape.perimeter());

**Comment by aizuyan** [comment]
@shuofenghao 
```js
class shape {
radius = 10;
perimeter = () => 2 * Math.PI * this.radius;
}
const newShape = new shape;
console.log(newShape.perimeter());

a = newShape.perimeter
a()
```

Above example also work, but not correct for normal function.

**Comment by ppaul** [comment]
The question is good, but isn't the correct answer D?
