### ISSUE TITLE
Question 28 

### ISSUE THREAD

**Issue by tom1mat** [lydiahallie/javascript-questions#521]
It actually returns nothing because `name.giveLydiaPizza()` is not logged. I think you should add `console.log(name.giveLydiaPizza())` or add a new option **Nothing**

**Comment by eduduardo** [comment]
I agree with @tom1mat with adding the `console.log()`, but don't agree with option D as correct.

**Comment by tom1mat** [comment]
> I agree with @tom1mat with adding the `console.log()`, but don't agree with option D as correct.

Its true! It should output nothing 😜.

I have just edited the comment :)
