### ISSUE TITLE
FIX THE QUESTION #55

### ISSUE THREAD

**Issue by ahmednadeem9112** [lydiahallie/javascript-questions#522]
THERE IS SOME ISSUE IN QUESTION NUMBER 55. WHEN YOU RUN THE CODE IN THE EDITOR IT WILL SHOW AN TYPE ERROR BECAUSE of THE pet.bark() IS DEFINED TWO TIME IN THE CODE SO REMOVE OUT THE pet.bark() FROM THE CODE SO IT WILL WORK.

**Comment by chinesedfan** [comment]
`TypeError` is the expected error, but not due to "defined" twice. You can check the explanations of it.
