### ISSUE TITLE
Seeking help

### ISSUE THREAD

**Issue by abedin911** [lydiahallie/javascript-questions#523]
Hello everyone,
I just completed the beginner fundamental topics of JS now what type of JS project should i do for enhanced my js skill
Thank you

**Comment by medic-code** [comment]
@abedin911 It may be worth posting on twitter, or reddit about these sorts of questions! Rather than opening up an issue. My advice would be to do something you're passionate about, or something you have in your life that is a frustration. Can't go wrong with that.

Should this issue be closed ?
