### ISSUE TITLE
Q135,opps!

### ISSUE THREAD

**Issue by ssvh** [lydiahallie/javascript-questions#543]
In this case, we pass the handler object which contained **_to_** properties
Should be：
In this case, we pass the handler object which contained **_two_** properties

**Comment by medic-code** [comment]
I just saw that this has been corrected, should this issue be closed ? 

https://github.com/lydiahallie/javascript-questions/commit/4224333da7cadd395006ee623ed6ba20fddc1686 for reference to the changes that have been merged.
