### ISSUE TITLE
Q98 error！！！

### ISSUE THREAD

**Issue by BM-laoli** [lydiahallie/javascript-questions#545]
I find a Error，in the question 98；I don’t know if it’s the Chinese translation，Maybe you need me to do Chinese translation。Maybe you need me to do Chinese translation。

![image](https://user-images.githubusercontent.com/60060313/109406029-c28a9880-79b0-11eb-93df-e44fcbac3bdd.png)

**Comment by PeiLiao** [comment]
I found this, too. The answer would be `SyntaxError`

**Comment by BM-laoli** [comment]
The author's original intention is:
 ```js
const getUser =  user => ( { name:user.name, age: user.age } );
```

**Comment by xurenda** [comment]
It is indeed `SyntaxError`
