### ISSUE TITLE
Question 28 output

### ISSUE THREAD

**Issue by tomcorke** [lydiahallie/javascript-questions#55]
The question asks what the output is, but there is no `console.log` as there is in other questions - while the `giveLydiaPizza` method does return the string as specified, it is never output.

This actually seems a little inconsistent across many questions, now that I look at them with this in mind.

**Comment by isthisstackoverflow** [comment]
If I just copy that code into my DevTools and hit that Enter button, it is the output since it is the final expression value. Or whatever that was called.

Just give Lydia pizza already!

**Comment by tomcorke** [comment]
I guess it's just more of an inconsistency in expecting console.log to give
output and the return value of a method, and is ultimately unimportant

**Comment by SandroMiguel** [comment]
The same thing happened to me. Ok, if you run the code in DevTools it shows the output but if you run the code in the codesandbox.io, you need to put the console.log to see the output.
