### ISSUE TITLE
Question 13 is not about javascript

### ISSUE THREAD

**Issue by pavelrevers** [lydiahallie/javascript-questions#56]
https://github.com/lydiahallie/javascript-questions/blob/master/README.md#13-what-are-the-three-phases-of-event-propagation

**Comment by thiagosaife** [comment]
> https://github.com/lydiahallie/javascript-questions/blob/master/README.md#13-what-are-the-three-phases-of-event-propagation

I disagree with you. Since events are handled with JavaScript, the question is all about JavaScript.

**Comment by kevinchung1026** [comment]
Strictly speaking, question 13 is about DOM

**Comment by thiagosaife** [comment]
@kevinchung1026 How do you deal with events in DOM?

**Comment by pavelrevers** [comment]
Typescript, Elm, Purescript? There are many options.

I will say more. If you open the javascript specification, then there is nothing about the events

**Comment by ptcc** [comment]
I think the answer is also wrong... 

> During the capturing phase, the event goes through the ancestor elements down to the target element

going through ancestor elements only allows traversing up the tree not down

**Comment by thiagosaife** [comment]
@pavelrevers From all those languages, one is a sintaxe sugar and the others compile to JavaScript. So no, unless you use another language that browser can interpret besides JavaScript (if you know more, please clarify), the question is about JavaScript. You can say more about this, too:
[https://developer.mozilla.org/en-US/docs/Web/API/Event](url)
It's about the DOM? Of course it is. But you cannot deny that JavaScript is responsible for dealing with events in DOM. You don't use CSS or HTML, Java or Python to deal with those things in browser. You use JavaScript, don't you?

**Comment by A1rPun** [comment]
What is this issue accomplishing exactly? Do you want this question removed @pavelrevers?

I can understand why people may think the question is out of place but please don't deny that JavaScript devs require at least some knowledge of other tech like for example HTML, DOM & CSS.

What are we gaining from the question? Knowledge!

**Comment by kevinchung1026** [comment]
> @kevinchung1026 How do you deal with events in DOM?

Of course JS, although this question is related with DOM. 
 In fact, I don't care these.😬

**Comment by lydiahallie** [comment]
I agree that it's about the DOM API, however most JavaScript developers will have to deal with this. If a certain question doesn't apply to you, feel free to skip it 😃
