### ISSUE TITLE
The answer to question 98 is incorrect.

### ISSUE THREAD

**Issue by hubiwibe** [lydiahallie/javascript-questions#563]
Hello everyone.

I think the answer to question 98 is wrong.

### Q. 98
```js
const getList = ([x, ...y]) => [x, y]
const getUser = user => { name: user.name, age: user.age }

const list = [1, 2, 3, 4]
const user = { name: "Lydia", age: 21 }

console.log(getList(list))
console.log(getUser(user))
```

A: [1, [2, 3, 4]] and undefined
B: [1, [2, 3, 4]] and { name: "Lydia", age: 21 }
C: [1, 2, 3, 4] and { name: "Lydia", age: 21 }
D: Error and { name: "Lydia", age: 21 }

### The result of my running
```js
const getUser = user => { name: user.name, age: user.age }
                                              ^
SyntaxError: Unexpected token ':'
```

What do you think?

**Comment by jcfreitas2000** [comment]
const getUser = user => ({ name: user.name, age: user.age })

We have to put the return between ( )

**Comment by Bittttter** [comment]
Maybe the
`const getUser = user => { name: user.name, age: user.age }`
in line2 should replace to
`const getUser = user => ({ name: user.name, age: user.age })`

**Comment by fabiancook** [comment]
The answer is correct if the returned "object" has one property 

```
const getUser = user => { name: user.name }
```

![image](https://user-images.githubusercontent.com/4337080/118904128-55622000-b96d-11eb-83b7-6fbcde037f80.png)

The answer is correct for the class of issue, maybe there is an engine out there that allows this syntax, and leads to the "single property object looking" definition behaviour

**Comment by hubiwibe** [comment]
@fabiancook 
Thank you for answer.
I learned something new.
Thank you.

**Comment by fabiancook** [comment]
It may be benifical for the answer to include the difference between the two. Node, chrome, safari, and firefox all present this syntax error for the more than one property case:

![image](https://user-images.githubusercontent.com/4337080/118904850-c0f8bd00-b96e-11eb-9657-bcc1250ebb16.png)
![image](https://user-images.githubusercontent.com/4337080/118904881-d1109c80-b96e-11eb-83fd-016d329ae1ee.png)
![image](https://user-images.githubusercontent.com/4337080/118904802-b0e0dd80-b96e-11eb-9756-56ec78bd6059.png)
![image](https://user-images.githubusercontent.com/4337080/118904922-ea194d80-b96e-11eb-86b9-0515ab766258.png)

Maybe the example in the question should just return the single property name and then it would be correct 😄

**Comment by ebinxavier** [comment]
Please change the object to a single property object like this `const getUser = user => { name: user.name }`, otherwise, the question won't be valid anymore.
