### ISSUE TITLE
How to prepare to answer the questions here 

### ISSUE THREAD

**Issue by arangates** [lydiahallie/javascript-questions#605]
i am thinking to read YDKJS books , but what do you people recommend ?

**Comment by aanhlle** [comment]
imo just learn the basics of JS, learn how JS works behind the scene.
some materials you can find online:
> udemy course (paid course)
> geekforgeeks (free)
then just do the questions, get wrong answers then review/learn the concept > repeat.

**Comment by jakeherp** [comment]
If you prefer books, my recommendation for years has been Eloquent JavaScript (you can read it for free [here](https://eloquentjavascript.net/) or buy the physical book), other than that freeCodeCamp is a great and very in depth resource to learn JS and other languages.
