### ISSUE TITLE
Question 34 Answer, FYI part

### ISSUE THREAD

**Issue by littlee** [lydiahallie/javascript-questions#607]
> FYI: there are only 7 built-in types: null, undefined, boolean, number, string, object, and symbol. "function" is not a type, since functions are objects, it's of type "object".

I think "function" is one of the types
```js
typeof function a() {} // "function"
```

**Comment by JayNewbie** [comment]
[](https://www.edureka.co/blog/data-types-in-javascript/) should answer your question :)
