### ISSUE TITLE
我想把它写在自己的公众号，可以么？

### ISSUE THREAD

**Issue by sorryjs** [lydiahallie/javascript-questions#61]
我想把它写在自己的公众号，可以么？

**Comment by edenyy** [comment]
no,you are not allowed

**Comment by wangzhen-CHN** [comment]
中文人家看不懂吧

**Comment by SuperTangKai** [comment]
我同意，谁反对

**Comment by zhaojianshu** [comment]
> 中文人家看不懂吧

这个不是作者翻译过来的地址么

**Comment by zhaojianshu** [comment]
> 我同意，谁反对

我的公众号，就我一个人

**Comment by lydiahallie** [comment]
Can I close this issue?

**Comment by Hsins** [comment]
> Can I close this issue?

Dear @lydiahallie, the man @sorryjs open this issue to ask your admission to share the contents to his "Wechat Official Account" (just like a group or platform that articles could be shared on it).

I think that you can close the issue. By the way, what the content he wanted to share is the Chinese version.
