### ISSUE TITLE
Question 76's answer is incorrect

### ISSUE THREAD

**Issue by parth23** [lydiahallie/javascript-questions#622]
https://github.com/lydiahallie/javascript-questions#76-whats-the-output

The answer to question number 76 should be 'C' undefined if we console.log(name).
And if the answer is correct then in question console log should be console.log(myName) instead of console.log(name)

**Comment by jakubreron** [comment]
It's `undefined` in the browser
But there is a `ReferenceError` in the node environment

![image](https://user-images.githubusercontent.com/25802053/141184394-6d71cee0-5b32-4c95-accb-29690d6b82be.png)

Shouldn't we take it into the consideration?

**Comment by efleurine** [comment]
One weird thing is that chrome returns `undefined` when it comes to `name` by default it seems.

**Comment by KNJON** [comment]
这台变量名用的有点问题，如果变量不是name而是n的话，答案确实是D。name是关键字了，所有console.log(name)是不会报错的

There is something wrong with the name of the variable. If the variable is n instead of name, the answer is indeed D. Console. log(name) will not return an error

**Comment by aayuushh365** [comment]
![image](https://user-images.githubusercontent.com/74130928/179492390-4f06a513-e9ef-42f8-b231-ae37afa1cc23.png)

I guess the answer of this question should be D. as name isn't defined in the scope. 

![image](https://user-images.githubusercontent.com/74130928/179492563-a59bc31d-8f24-4b61-9c97-239830b53042.png)

But on console logging to myName , the output shows `Lydia`. 
![image](https://user-images.githubusercontent.com/74130928/179492771-9456d131-d4c3-40da-8eab-7e81b1375a2a.png)

**Comment by SeyyedKhandon** [comment]
I've provided the complete answer in this [merge request](https://github.com/lydiahallie/javascript-questions/pull/698).
