### ISSUE TITLE
Question 39 -wrong type structure.

### ISSUE THREAD

**Issue by omgpiu** [lydiahallie/javascript-questions#632]
According ECMA-262 we don't have primitive types.
We have primitive values  https://tc39.es/ecma262/#sec-primitive-value
and types : boolean, null, undefined, bigint, number, string, symbol, object  . https://tc39.es/ecma262/#sec-type (4.4.5 primitive value) 

In ECMA there isn't any word about primitive types. Check it in ECMA  menu 4.4

**Comment by kizob123** [comment]
I think it mentions it. It explains that a primitive value is a member of any built-in type. Built-in types are Boolean, Number, Null, Undefined, String, Bigint, Symbol...
