### ISSUE TITLE
Question related to react/js/execution/es6

### ISSUE THREAD

**Issue by 12sam12** [lydiahallie/javascript-questions#640]
Lets consider the following screenshot:
![image](https://user-images.githubusercontent.com/13358855/149645488-c515f9e1-140c-4843-aea5-d657797b33ab.png)
![image](https://user-images.githubusercontent.com/13358855/149645544-bb32c50e-f7bd-4670-8a32-c01ee4bf8703.png)

Even after the control reaches the let assignment statement, the previous imports are undefined. Could anyone explain why is that so?
Also the following shows that the bundled internal variables are defined though:
![image](https://user-images.githubusercontent.com/13358855/149645560-e0595dfe-bdfc-494d-8a07-f373a2a7095a.png)
![image](https://user-images.githubusercontent.com/13358855/149645562-10f8ed38-7309-48a9-ac18-31c8430e3ff1.png)
Why does this behavior exist in javascript? Is this expected or something different.
Its in mozilla firefox browser (95.0.1)

**Comment by merveilkanku** [comment]
It's right

**Comment by 12sam12** [comment]
Ok then if I call and run the rootSaga in the bottom of the file, it doesnt start the saga as the Saga stays undefined I guess. Why is this happening and when will all the imports have valid values? Pl give your answer in a more descriptive manner instead of just saying that this behavior is expected, which kind of triggers more questions.
