### ISSUE TITLE
Join us as a guest on JS Party?! 🎉

### ISSUE THREAD

**Issue by jerodsanto** [lydiahallie/javascript-questions#65]
👋 @lydiahallie nice job on this repo! Wow, it's really blowing up 👏 

We'd love to have you join us sometime soon on [JS Party](https://changelog.com/jsparty), the most fun (IMHO!) JavaScript/web focused podcast in the 'Verse!

Interested at all? Holler back here or email me jerod@changelog.com if you'd rather chat privately.

Keep up the good work! 💚

**Comment by lydiahallie** [comment]
Can you please reach out to me on LinkedIn? Link in bio 😄
