### ISSUE TITLE
Question 3's Explanation

### ISSUE THREAD

**Issue by oosharma** [lydiahallie/javascript-questions#652]
The last line in the answer's explanation, "There is no value radius on that object, which returns NaN" could probably be the following for more clarity- 

"There is no value radius on that object, which returns undefined, which when multiplied by Math.PI returns NaN." 

3. What's the output?
const shape = {
  radius: 10,
  diameter() {
    return this.radius * 2;
  },
  perimeter: () => 2 * Math.PI * this.radius,
};

console.log(shape.diameter());
console.log(shape.perimeter());

A: 20 and 62.83185307179586
B: 20 and NaN
C: 20 and 63
D: NaN and 63

Answer: B
Note that the value of diameter is a regular function, whereas the value of perimeter is an arrow function.

With arrow functions, the this keyword refers to its current surrounding scope, unlike regular functions! This means that when we call perimeter, it doesn't refer to the shape object, but to its surrounding scope (window for example).

There is no value radius on that object, which returns NaN.

**Comment by jakeherp** [comment]
Please feel free to open a PR with your suggestions.
