### ISSUE TITLE
Make me a collabrator. I will add Uzbek language.

### ISSUE THREAD

**Issue by otabekoff** [lydiahallie/javascript-questions#668]
I can't present full translation at once. So make me a collabrator. I will translate one by one.

**Comment by otabekoff** [comment]
Also, let's add Github pages.

**Comment by pjalsGit** [comment]
You don't need to be a collaborator to make changes, fork the repository and make a pull request with your changes.

**Comment by jakeherp** [comment]
Closing issue, feel free to open a PR to add Uzbek translations and I'm happy to approve.
