### ISSUE TITLE
Question No. 37

### ISSUE THREAD

**Issue by rajanmagar** [lydiahallie/javascript-questions#674]
Hello @lydiahallie,
Great job first of all. While going through the QA i found little correction. The answer of 37 is correct but the order of element is wrong.
Given: [1, 2, 3, 7 x empty, 11]  ❌
Correct: [1, 2, 3, empty x 7, 11] ✅
Sharing the screenshot for more clarity.
<img width="625" alt="Screenshot 2022-08-07 at 4 09 25 AM" src="https://user-images.githubusercontent.com/39592375/183268100-c4c027d2-7e70-47fc-aca4-d7aa1855df59.png">

I will fix it. Sending PR soon.
Happy Learning.
Regards,
Rajan

**Comment by contributorpw** [comment]
#675
