### ISSUE TITLE
Question 14: All objects have prototypes

### ISSUE THREAD

**Issue by stuymedova** [lydiahallie/javascript-questions#689]
I've researched some information on this, the [MDN](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes) states:
> Every object in JavaScript has a built-in property, which is called its prototype. The prototype is itself an object, so the prototype will have its own prototype, making what's called a prototype chain. The chain ends when we reach a prototype that has null for its own prototype.

My understanding is that every object has a prototype and the last one in the chain has `null` for its value. I couldn't find any information on the "base object". I'd suggest that perhaps the answer may be incorrect.

**Comment by black1277** [comment]
`const noPrototype = Object.create(null);
 console.log(noPrototype.toString());
   // throws an error noPrototype.toString is not a function 
`
