### ISSUE TITLE
Question 76

### ISSUE THREAD

**Issue by gabilita** [lydiahallie/javascript-questions#699]
Congrats on the questions, but I think you made an error on question `76`.
Probably because you were in an iframe or something and had the `window.name` property.
The correct answer is `D` since it's returning a ReferenceError.
Maybe you could change the property to something different.

```js
const { myName: otherName } = { myName: 'Lydia' };

console.log(myName); // Uncaught ReferenceError: myName is not defined
```

**Comment by wodin** [comment]
Hi. There's another issue about this here: #622

There are also several open PRs for this:
#698
#686
#670
#628

I am not involved with this project, so can't tell you any more than the above.

**Comment by gabilita** [comment]
Thanks, then I'll be closing this.
