### ISSUE TITLE
Add new question

### ISSUE THREAD

**Issue by k-sai-kiranmayee** [lydiahallie/javascript-questions#720]
Hello all!

Thank you for your outstanding work and for making such a significant contribution and maintaining this repository to the programming community.

I would like to contribute by adding a question/answer I came to know recently.

Kindly let me know if it's okay and also if to post the question directly here.

Thanks and Regards,
K. Sai Kiranmayee

**Comment by jakeherp** [comment]
You can open a PR with the question you want to add, so we can evaluate whether to add it.
