### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by Louiswealthy** [lydiahallie/javascript-questions#723]
How do i differentiate variables ?

**Comment by jakeherp** [comment]
Can you explain a bit more what you mean by that? Assigning a value to a variable makes it differentiable from other values.

```javascript
const a = 5
const b = 2
const sum = a + b
```

Is a simple example of that.

**Comment by Akashraj161** [comment]
If you assign a value to a variable without quotes, it will be treated as a number.
 example:  let a = 11
And if you assign a value to a variable inside quotes, it will be treated as a string.
example:  let b = "This is string"

**Comment by jakeherp** [comment]
Closing as this was answered above.
