### ISSUE TITLE
Question 10's answer translated in Vietnamese is incorrect!

### ISSUE THREAD

**Issue by duyvuxx** [lydiahallie/javascript-questions#726]
In this answer, everything is correct, but the additional information is completely wrong, causing confusion for those seeking accurate information.

Here is a proposed revision of the additional information in Vietnamese:

"Các kiểu dữ liệu khác ngoài các kiểu nguyên thủy đều là kiểu dữ liệu tham chiếu."

![fix](https://github.com/lydiahallie/javascript-questions/assets/117933447/8f0b7af0-ac41-4da2-ba75-f159930d00eb)

**Comment by jakeherp** [comment]
Closing as the fix was merged
