### ISSUE TITLE
Question regarding translating questions into Bangla

### ISSUE THREAD

**Issue by nerdjfpb** [lydiahallie/javascript-questions#746]
I was wondering if I could translate these questions into Bangla.

But I want to use chatGPT while doing it. As a native speaker (Bangla) I can fix where chatGPT mess up. 

Is this okay?

Thanks

**Comment by jakeherp** [comment]
Sure, feel free to open a PR to add Bangla as a language. You can keep it as a draft until it's ready to be reviewed. You don't have to translate all at once, but before we merge the PR there should be a good number of questions ready (~50 would be good).

Thanks for your help!

**Comment by nerdjfpb** [comment]
Thanks @jakeherp On it 🚀
