### ISSUE TITLE
Unable to push changes for creating a PR

### ISSUE THREAD

**Issue by k-sai-kiranmayee** [lydiahallie/javascript-questions#758]
Hello,

   Firstly great repo! I'm trying to make a contribution.

Have cloned the repo locally, and added a question, and when trying to push after creating a branch, it is saying
```
remote: Permission to lydiahallie/javascript-questions.git denied to k-sai-kiranmayee.
fatal: unable to access 'https://github.com/lydiahallie/javascript-questions.git/': The requested URL returned error: 403  
```
I don't have the SSH key. Looking forward to contribute and learn, any help is much appreciated 🤞 

Thanks,
K. Sai Kiranmayee

**Comment by alexandercerutti** [comment]
You have to fork it, not just clone it.
You fork it, clone your fork and then open the PR.

**Comment by k-sai-kiranmayee** [comment]
Thank you @alexandercerutti for your quick response! 😄 

My current Git username is linked to my current organization. So, there is no other way to raise PR without forking it? If there is any, please let me know, I will be glad!!

Thanks!

**Comment by alexandercerutti** [comment]
Nope, you should be the owner or maintainer of the repo.

Is there any issue for it to be linked to your organization?

Mine is linked too but I use it for both open-source and personal things (I do have three emails registered in the same profile, so one is for the job and one for personal things + recovery).

**Comment by k-sai-kiranmayee** [comment]
Thank you @alexandercerutti, I have added my personal mail to this itself. Closing this!
