### ISSUE TITLE
61 question answer is wrong , answer is D instead of B , because when the property has enumerable is false it didn't appear in Objects.keys,for in and also didn't appear when console it but the property will still exist in the object.

### ISSUE THREAD

**Issue by subramanyam12** [lydiahallie/javascript-questions#769]
const person = { name: 'Lydia' };
Object.defineProperty(person, 'age', { value: 21 });
console.log(person);
console.log(Object.keys(person));

A: { name: "Lydia", age: 21 }, ["name", "age"]
B: { name: "Lydia", age: 21 }, ["name"]
C: { name: "Lydia"}, ["name", "age"]
D: { name: "Lydia"}, ["age"]

**Comment by yashug** [comment]
@subramanyam12 the answer is B only. just check this in your browser console.

![Screenshot 2024-02-22 at 10 11 55 PM](https://github.com/lydiahallie/javascript-questions/assets/14201280/84264639-85b6-472b-b5e6-b90114ec995f)
