### ISSUE TITLE
Questions 30 , why third print before second

### ISSUE THREAD

**Issue by RahulSingh044** [lydiahallie/javascript-questions#771]
As the timeout is not specified then how third print before second...

**Comment by alexandercerutti** [comment]
Default is 0ms (which, actually, becomes something like 4ms in Chrome and I don't know what else is other engines).

Which means that the callback inside it, is **scheduled** (not executed) to be run as soon as the stack is empty. When a time is specified, browser will let the timer expire before scheduling the callback run.

**Comment by yashug** [comment]
@RahulSingh044 the default is 0s and immediately it will be pushed to callback queue by web API. Then event loop moves this into call stack. 

more details you can get it by reading this https://dev.to/lydiahallie/javascript-visualized-event-loop-3dif

**Comment by RahulSingh044** [comment]
thanks for the help ... it's clear now..
