### ISSUE TITLE
Error in answer for question 34

### ISSUE THREAD

**Issue by TrevorBurnham** [lydiahallie/javascript-questions#79]
The answer to question 34 says:

> "function" is not a type, since functions are objects, it's of type "object".

A quick REPL session shows otherwise:

```
> typeof function() {}
"function"
> typeof (() => {})
"function"
```

As to the other claim in the answer:

> FYI: there are only 7 built-in types

This is also dubious. Compare to: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#Description

**Comment by lydiahallie** [comment]
Thanks for your input! You are right, this has been fixed now. Since I explained it in another question, I removed the FYI section.
